questions=[
    "How would you describe your overall mood lately?",
    "Are you able to enjoy activities that used to bring you pleasure?",
    "How well are you sleeping, and do you feel rested when you wake up?",
    "Have you noticed changes in your appetite or weight recently?",
    "Are you able to concentrate on tasks, or do you find your mind wandering?",
    "Do you often feel fatigued or lacking in energy?",
    "How would you describe your stress levels currently?",
    "Have you experienced any significant life changes or stressors recently?",
    "Are you finding it easy to make decisions, or do you feel indecisive?",
    "How is your self-esteem and confidence these days?",
    "Are you able to maintain a healthy work-life balance?",
    "Do you have a support system you can rely on when needed?",
    "Have you been isolating yourself from friends or family?",
    "How do you cope with challenges and setbacks?",
    "Have you experienced changes in your interest or motivation levels?",
    "Are you experiencing any physical symptoms without a clear medical cause?",
    "How do you view the future? Are you optimistic or pessimistic?",
    "Are you experiencing any intrusive or distressing thoughts?",
    "How would you rate your overall satisfaction with your life right now?",
    "Have you had thoughts of self-harm or suicide?",
    "How do you handle stress in your daily life?",
    "Are there any unresolved issues from your past that still affect you?",
    "How well do you feel you communicate with others?",
    "Are you satisfied with your current level of social interaction?",
    "How do you prioritize self-care and relaxation?",
    "Do you have healthy coping mechanisms for dealing with difficult emotions?",
    "Are there specific triggers that worsen your mood or anxiety?",
    "What activities bring you a sense of purpose and fulfillment?",
    "How do you set and work towards personal goals?",
    "Are you content with your current work or academic situation?",
    "How do you handle conflicts in your relationships?",
    "Are there habits or behaviors you would like to change?",
    "How often do you experience feelings of loneliness?",
    "Are you able to express your emotions in a healthy way?",
    "How would you describe your relationship with food?",
    "Do you engage in activities that promote relaxation and mindfulness?",
    "How do you perceive and respond to criticism?",
    "Are there aspects of your life that you find particularly challenging?",
    "How is your physical health, and do you engage in regular exercise?",
    "What role does spirituality or a sense of purpose play in your life?",
    "How do you feel about your current level of productivity?",
    "Are you satisfied with your sleep patterns and quality of sleep?",
    "How do you navigate and manage change in your life?",
    "Do you have a history of trauma, and have you sought support for it?",
    "How do you balance personal and professional commitments?",
    "What role do hobbies or creative outlets play in your life?",
    "How do you handle feelings of guilt or shame?",
    "Are there areas of your life where you feel a lack of control?",
    "How do you respond to unexpected challenges or setbacks?",
    "Are there patterns of thinking that contribute to negative emotions?",
    "How connected do you feel to your local community?",
    "Do you feel a sense of belonging and acceptance in your relationships?",
    "How do you practice gratitude in your daily life?",
    "Are you open to seeking professional help if needed?",
    "How do you set boundaries in your personal and professional life?",
    "How do you handle changes in your routine or schedule?",
    "What strategies do you use to manage your time effectively?",
    "Are there any unmet needs or desires that impact your well-being?",
    "How do you define and pursue a sense of personal growth?",
    "How do you recharge and find joy in your everyday life?",
    "Are there unresolved conflicts within your family or social circles?",
    "How do you differentiate between healthy and unhealthy relationships?",
    "What steps do you take to maintain a positive mindset?",
    "How do you navigate societal or cultural expectations that impact you?",
    "How do you feel about your financial situation and stability?",
    "Are there aspects of your identity that you struggle with or celebrate?",
    "How do you prioritize and maintain connections with loved ones?",
    "What steps do you take to manage and reduce feelings of overwhelm?",
    "How do you perceive and manage your self-worth?",
    "Are you aware of and able to challenge negative self-talk?",
    "How do you handle change, and does it impact your mental well-being?",
    "What role does humor play in your life, and do you find moments to laugh?",
    "How do you nurture and maintain a positive self-image?",
    "Are there aspects of your daily routine that contribute to your happiness?",
    "How do you manage and express feelings of anger or frustration?",
    "Do you feel a sense of balance between work, rest, and leisure activities?",
    "How would you describe your relationship with technology and social media?",
    "Are there specific fears or anxieties that regularly occupy your thoughts?",
    "How do you express and receive love in your relationships?",
    "What steps do you take to maintain a healthy work-life balance?",
    "Are there past achievements that you're proud of and reflect on?",
    "How do you handle periods of uncertainty about the future?",
    "What role does nature or outdoor activities play in your well-being?",
    "Are you able to forgive yourself for past mistakes or shortcomings?",
    "How do you set and respect personal boundaries in your relationships?",
    "What steps do you take to recharge and rejuvenate during tough times?",
    "How do you define success, and does it contribute to your happiness?",
    "Are there negative thought patterns that you're actively working to change?",
    "How do you approach and manage feelings of loneliness or isolation?",
    "What steps do you take to manage and reduce stress in your life?",
    "How do you respond to feedback, both positive and constructive?",
    "Are there aspects of your life where you feel a sense of purpose?",
    "How do you prioritize self-compassion and self-care?",
    "What strategies do you use to cope with unexpected life challenges?",
    "How do you maintain a sense of hope and optimism for the future?",
    "Are there cultural or societal expectations that impact your mental health?",
    "How do you build and maintain a sense of community and support?",
    "What steps do you take to stay connected to your emotions?",
    "How do you navigate and cope with feelings of guilt or shame?",
    "Are there specific mindfulness or relaxation practices you engage in?",
    ]